Adds an attribute called IgnoreProperty that tells the generator to skip the property
StefH/FluentBuilder pull request #44
Opened 2022-06-30 20:11 UTC by emorell96

I added an attribute that allows the user to set some properties as ignored for more control when generating a builder.

It allows me to bypass #43 by ignoring the property that breaks the code.

I tested the attribute by adding it to the SimpleClass and the test `FluentBuilderGeneratorTests.FluentBuilderSourceGeneratorTests.GenerateFiles_ForSimpleClass_Should_GenerateCorrectFiles` should fail if the property is not skipped since the generated code wouldn't match the expected code.

The test passes, as do all the others:
![image](https://user-images.githubusercontent.com/20151415/176769084-2afea9ff-faae-4fdb-92b4-af0dd42e890e.png)

2022-06-30 21:16 UTC, emorell96 commented
Ok this PR is ready. I have moved the attribute to the Attribute Generator. And it works as expected.

2022-07-01 06:30 UTC, StefH requested changes

2022-07-01 06:30 UTC, StefH commented on src/FluentBuilderGenerator/FileGenerators/AutoGenerateBuilderAttributeGenerator.cs
> +//     This code was generated by https://github.com/StefH/FluentBuilder version {System.Reflection.Assembly.GetExecutingAssembly().GetName().Version}
Nice addition.

Can you add this to all generated classes?

2022-07-01 06:30 UTC, StefH commented on src/FluentBuilderGenerator/FileGenerators/FluentBuilderClassesGenerator.cs
> +    private const string IgnoreAttributeClassName = "FluentBuilder.IgnorePropertyAttribute";
move const to top of the file

2022-07-01 15:51 UTC, StefH commented
@emorell96 
thank you.

please see my code review

2022-07-01 15:52 UTC, emorell96 commented
I'll get to them during the weekend :) I think they are a good idea.

2022-07-09 13:45 UTC, StefH commented
@emorell96 Did you have time yet to fix the comments?

2022-07-10 12:21 UTC, StefH commented
@emorell96 If you don't have the time, that's also fine. I can take over your branch/PR and update it.

2022-07-12 16:51 UTC, merged