Take the namespace of generated files from the RootNamespace property
StefH/FluentBuilder pull request #50
Opened 2022-10-11 01:54 UTC by justinwritescode

Change to take the namespace from the RootNamespace property instead of from the AssemblyName.  This makes the generated code configurable.

2022-10-11 07:20 UTC, StefH commented
@justinwritescode 
Did you use a different newline for the files? Because it seems that all lines are changed?

2022-10-11 07:33 UTC, justinwritescode commented
I wrote it on a Mac....sorry....

2022-10-11 07:40 UTC, justinwritescode commented
Ah...yes...it must be the line endings.  When I click "Hide whitespace changes" it shows up fine. Sorry about that....

2022-10-11 12:32 UTC, StefH commented
Can you edit this on a windows pc ? Or change the line-endings to CRLF?

2022-10-11 19:43 UTC, justinwritescode commented
Actually, it looks like your line endings are inconsistent.  Have a look at IFileGenerator.cs.  On the left is the repo code, right is a version I just opened and saved with CRLF endings.

![image](https://user-images.githubusercontent.com/107151986/195181759-7ab6e146-46c9-4373-b507-0b31b92c928d.png)

And here's FluentBuilderClassesGenerator.IDictionary.cs:

![image](https://user-images.githubusercontent.com/107151986/195183945-415783f2-2d39-4c75-9f49-c78ce29002a8.png)

And here's Header.cs:

![image](https://user-images.githubusercontent.com/107151986/195183821-703cd971-4229-48c8-a69d-bf6dfc8b2419.png)

I checked some of the others I didn't touch and it looks like your files pretty much alternate CRLF and LF line endings....

Anyway, these all have consistent CRLF line endings now.  If it's too confusing for you to look at, you can click the gear icon in the diff viewer and click "Hide whitespace" as shown below.

![image](https://user-images.githubusercontent.com/107151986/195183680-da500b5f-0a11-4db2-942a-6ecc11144bb2.png)

Cheers! And thanks for a great lib!

2022-10-11 19:52 UTC, StefH commented
I will take a look tomorrow.

Thank you for investigating.

2022-10-12 06:27 UTC, StefH requested changes
1. Can you write some comments in your PR on how that "build_property.RootNamespace" should be used? (Then I will copy to this to the readme)
2. And can you add a unit-test for this change? (Maybe you need a new test-project for this?)

2022-10-12 06:27 UTC, StefH commented on src/FluentBuilderGenerator/Wrappers/IGeneratorExecutionContextWrapper.cs
> +    public string NamespaceName { get; }
Can you add some comment for this new property?

2022-10-14 08:31 UTC, StefH commented
@justinwritescode 
Did you have time yet  to check my review comments?

2022-10-16 17:07 UTC, justinwritescode commented
Yes but I haven't had time to implement yet...

2023-01-15 09:56 UTC, merged